
[sign]
DefaultName = 'SIGN_DEFAULT_NAME'
Draw = 'sign'
Size = [1, 1]
Usable = true
UseText = 'read'
Blocking = true
UseFunc = 'use_sign'
[[sign.fields]]
Name = 'message'
Type = 'string'

[door]
DefaultName = 'DOOR_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'enter'
Blocking = true
UseFunc = 'use_door'
[[door.fields]]
Name = 'target_zone'
Type = 'zone'
[[door.fields]]
Name = 'x'
Type = 'int'
[[door.fields]]
Name = 'y'
Type = 'int'

[item_spawner]
DefaultName = 'ITEM_SPAWNER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'spawn_item'
[[item_spawner.fields]]
Name = 'target_zone'
Type = 'item'
[[item_spawner.fields]]
Name = 'x'
Type = 'int'
[[item_spawner.fields]]
Name = 'y'
Type = 'int'

[item_modifier]
DefaultName = 'ITEM_MODIFIER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'modify_item'
[[item_modifier.fields]]
Name = 'item_mod'
Type = 'item_mod'
[[item_modifier.fields]]
Name = 'target_slot'
Type = 'slot'

[npc_spawner]
DefaultName = 'NPC_SPAWNER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'spawn_npc'
[[npc_spawner.fields]]
Name = 'npc'
Type = 'npc'
[[npc_spawner.fields]]
Name = 'x'
Type = 'int'
[[npc_spawner.fields]]
Name = 'y'
Type = 'int'

[dummy]
DefaultName = 'training dummy'
Size = [1, 1]
Usable = true
UseText = 'attack'
Blocking = true
UseFunc = 'attack_dummy'

[corpse]
DefaultName = 'corpse'
Size = [1, 1]
Blocking = false
[[corpse.fields]]
Name = 'target_zone'
Type = 'type'
Export = true

[house]
DefaultName = 'house'
Size = [4, 2]
Blocking = true