
[sign]
DefaultName = 'SIGN_DEFAULT_NAME'
Draw = 'sign'
Size = [1, 1]
Usable = true
UseText = 'read'
Blocking = true
UseFunc = 'use_sign'
Strings = ['message']

[door]
DefaultName = 'DOOR_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'enter'
Blocking = true
UseFunc = 'use_door'
Strings = ['target_zone']
Ints = ['x', 'y']

[item_spawner]
DefaultName = 'ITEM_SPAWNER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'spawn_item'
Strings = ['item_id']
Ints = ['x', 'y']

[item_modifier]
DefaultName = 'ITEM_MODIFIER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'modify_item'
Strings = ['item_mod_id', 'target_slot']

[npc_spawner]
DefaultName = 'NPC_SPAWNER_DEFAULT_NAME'
Size = [1, 1]
Usable = true
UseText = 'activate'
Blocking = true
UseFunc = 'spawn_npc'
Strings = ['npc_id']
Ints = ['x', 'y']

[dummy]
DefaultName = 'training dummy'
Size = [1, 1]
Usable = true
UseText = 'attack'
Blocking = true
UseFunc = 'attack_dummy'

[corpse]
DefaultName = 'corpse'
Size = [1, 1]
Blocking = false
Strings = ['type']
ExportStrings = ['type']

[house]
DefaultName = 'house'
Size = [4, 2]
Blocking = true