
[sunglasses]
Quality = 1
Name = 'Sunglasses'
Type = 'helmet'
MaxQty = 1
Durability = 9999
Special = ['sunglasses']
[sunglasses.requirements]
cool = 99
[sunglasses.stats]
defense_phys = 1
defense_magic = 1

[sword]
Quality = 2
Name = 'sword'
Type = 'melee'
MaxQty = 1
Durability = 9999
[sword.stats]
attack_phys = 5

[potion]
Quality = 1
Name = 'Potion'
Type = 'consumable'
MaxQty = 1
Durability = 9999
Special = ['consumable']
[potion.requirements]
[potion.stats]
restore_hp = 10