
[sunglasses]
Quality = 1
Name = 'Sunglasses'
Type = 'helmet'
MaxQty = 1
Durability = 9999
Price = 10
[sunglasses.Special]
Sunglasses = true
[sunglasses.requirements]
cool = 99
[sunglasses.stats]
DefensePhys = 1
DefenseMagic = 1

[sword]
Quality = 2
Name = 'sword'
Type = 'melee'
MaxQty = 1
Durability = 9999
Price = 10
[sword.stats]
AttackPhys = 5

[dagger]
Quality = 6
Name = 'crit thing'
Type = 'melee'
MaxQty = 1
Durability = 9999
Price = 10
[dagger.Stats]
CriticalChance = 20
AttackPhys = -5

[potion]
Quality = 1
Name = 'Potion'
Type = 'consumable'
MaxQty = 1
Durability = 9999
Price = 10
[potion.special]
Consumable = true
[potion.stats]
restore_hp = 10