
[fireball]
Name = 'fireball'
Level = 0
Cost = 1
Effects = [
    {Type = 'effect', Effect = 'fireball', Duration = 7, Origin = 'player', Target = 'target'},
    {Type = 'aoe', Effect = 'fire', Duration = 0, Range = 1, Damage = 5, Target = 'enemies'},
    # {Type = 'apply', Effect = 'fire', Duration = 0, Range = 2, Damage = 1},
]

[icebolt]
Name = 'ice bolt'
Level = 0
Cost = 2
Effects = [
    {Type = 'effect', Effect = 'icebolt', Duration = 3, Origin = 'player', Target = 'target'},
    {Type = 'aoe', Effect = 'ice', Duration = 0, Range = 0, Damage = 10, Target = 'enemies'},
]

[thunderbolt]
Name = 'thunderbolt'
Level = 0
Cost = 4
Effects = [
    {Type = 'effect', Effect = 'lightning', Duration = 0, Origin = 'player', Target = 'target'},
    {Type = 'aoe', Effect = 'shock', Duration = 0, Range = 0, Damage = 20, Target = 'enemies'},
]