
[[tile]]
Name = 'blank'
Blocking = false
[[tile]]
Name = 'blank'
Blocking = false
[[tile]]
Name = 'default'
Blocking = false
[[tile]]
Name = 'grass'
Blocking = false
[[tile]]
Name = 'water'
Blocking = true
[[tile]]
Name = 'trees'
Blocking = true
[[tile]]
Name = 'rocks'
Blocking = true