
SpawnPoint = [1, 4]
Width = 5
Height = 6
Map = [
    'default', 'default', 'default', 'default', 'default',
    'default', 'default', 'default', 'default', 'default',
    'default', 'default', 'default', 'default', 'default',
    'default', 'default', 'default', 'default', 'default',
    'default', 'default', 'default', 'default', 'default',
    'default', 'default', 'default', 'default', 'default',
]

[[Entity]]
Name = 'exit'
Type = 'door'
Position = [1, 5]
[Entity.Strings]
target_zone = 'start'
[Entity.Ints]
x = 6
y = 2