
SpawnPoint = [1, 1]
Width = 11
Height = 8
Map = [
    'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
]

[[Entity]]
Name = 'welcome sign'
Type = 'sign'
Position = [3, 0]
[Entity.Strings]
message = 'Welcome!'

[[Entity]]
Name = 'house'
Type = 'house'
Position = [5, 0]

[[Entity]]
Name = 'shop'
Type = 'door'
Position = [6, 1]
[Entity.Strings]
target_zone = 'house'

[[Entity]]
Name = 'exit'
Type = 'door'
Position = [10, 3]
[Entity.Strings]
target_zone = 'test'
[Entity.Ints]
x = 1
y = 3

[[Entity]]
Name = 'item spawner'
Type = 'item_spawner'
Position = [2, 0]
[Entity.Strings]
item_id = 'sunglasses'
[Entity.Ints]
x = 2
y = 1