
SpawnPoint = [1, 1]
Width = 6
Height = 8
Map = [
    'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
]

[[Entity]]
Name = 'Welcome Sign'
Type = 'sign'
Position = [3, 0]
[Entity.Strings]
message = 'Welcome!'

[[Entity]]
Name = 'Exit'
Type = 'door'
Position = [5, 3]
[Entity.Strings]
target_zone = 'test'
[Entity.Ints]
x = 1
y = 3

[[Entity]]
Name = 'Item Spawner'
Type = 'item_spawner'
Position = [2, 0]
[Entity.Strings]
item_id = 'sunglasses'
[Entity.Ints]
x = 2
y = 1