
SpawnPoint = [1, 1]
Width = 6
Height = 6
Map = [
    'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'default', 'default', 'default', 'default', 'default',
]

[[Entity]]
Name = 'Welcome Sign'
Type = 'sign'
Position = [2, 2]
[Entity.Strings]
message = 'Welcome!'

[[Entity]]
Name = 'Welcome Sign 2'
Type = 'sign'
Position = [3, 2]
[Entity.Strings]
message = 'Enjoy your stay!'