
SpawnPoint = [1, 1]
Width = 6
Height = 8
Map = [
    'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
]

[[Entity]]
Name = 'Exit'
Type = 'door'
Position = [0, 3]
[Entity.Strings]
target_zone = 'start'
[Entity.Ints]
x = 4
y = 3