
SpawnPoint = [1, 1]
Width = 6
Height = 8
Map = [
    'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'default',
]

[[Entity]]
Name = 'exit'
Type = 'door'
Position = [0, 3]
[Entity.Strings]
target_zone = 'start'
[Entity.Ints]
x = 4
y = 3

[[Entity]]
Type = 'dummy'
Position = [3, 3]

[[Entity]]
Name = 'item spawner'
Type = 'item_spawner'
Position = [2, 0]
[Entity.Strings]
item_id = 'sword'
[Entity.Ints]
x = 2
y = 1

[[NPC]]
Name = 'bolb'
Type = 'blob'
Position = [4, 1]