
SpawnPoint = [1, 1]
Width = 10
Height = 10
Map = [
    'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
    'default', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'default',
]

[[Entity]]
Name = 'exit'
Type = 'door'
Position = [0, 3]
[Entity.Strings]
target_zone = 'start'
[Entity.Ints]
x = 4
y = 3

[[Entity]]
Type = 'dummy'
Position = [3, 5]
[[Entity]]
Type = 'dummy'
Position = [5, 5]
[[Entity]]
Type = 'dummy'
Position = [7, 5]

[[Entity]]
Name = 'item spawner'
Type = 'item_spawner'
Position = [2, 0]
[Entity.Strings]
item_id = 'sword'
[Entity.Ints]
x = 2
y = 1

[[Entity]]
Type = 'npc_spawner'
Position = [6, 0]
[Entity.Strings]
npc_id = 'blob'
[Entity.Ints]
x = 6
y = 1